### ISSUE TITLE
If an m.room.encryption event is redacted, we think the room is no longer encrypted

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-meta#1501]

**Comment by richvdh** [comment]
I think this was incorrectly transferred from element-web. It appears to be specifically talking about element-web. Other platforms have other implementations and different behaviour.

**Comment by richvdh** [comment]
Actually, I was unable to reproduce this on (legacy) element-web, and it will be fixed by https://github.com/vector-im/element-web/issues/26108 for Element Web R.

All clients *should* keep a record of which rooms are encrypted, and ignore attempts to turn it off. If anyone can reproduce this behaviour, please file issues against the client concerned (with clear repro steps, unlike this issue).
